// nuxt-taiwind-blog/components/App/Footer.vue
<script lang="ts" setup></script>

<template>
  <footer class="px-4 text-white bg-gray-800 sm:px-0">
    <div 
      class="container flex flex-col justify-between gap-2 py-4 mx-auto sm:flex-row max-w-7xl lg:px-8"
    >
      <a href="#" class="text-lg font-semibold text-white">Nuxt Tailwind</a>
      <div class="text-sm">
        Nuxt Tailwind by
        <a href="#" class="font-semibold text-white">IT Genius</a>
        . All rights reserved
      </div>
    </div>
  </footer>
</template>

<style scoped></style>

// day5/basic-nextjs-typescript/src/components/Footer.tsx

import React from "react"

type props = {}

export default function Footer() {
    return (
        <footer className="flex justify-center items-center p-4 bg-gray-800 text-white">
            <div className="text-lg font-bold">Myapp</div>
            <div className="ml-4"> 2026 MyApp. All rights reserved.</div>
        </footer>
    )
}
