// nuxt-taiwind-blog/components/App/Footer.vue
<script lang="ts" setup></script>

<template>
  <footer class="px-4 text-white bg-gray-800 sm:px-0">
    <div 
      class="container flex flex-col justify-between gap-2 py-4 mx-auto sm:flex-row max-w-7xl lg:px-8"
    >
      <a href="#" class="text-lg font-semibold text-white">Nuxt Tailwind</a>
      <div class="text-sm">
        Nuxt Tailwind by
        <a href="#" class="font-semibold text-white">IT Genius</a>
        . All rights reserved
      </div>
    </div>
  </footer>
</template>

<style scoped></style>

// day5/basic-nextjs-typescript/src/components/admin/Footer.tsx
import React from "react"

type props = {}

export default function Footer({}: props) {
    return (
        <footer className="bg-white border-t border-gray-200 shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-900 dark:border-gray-700">
            <div className="w-full mx-auto  p-4 md:flex md:items-center md:justify-between">
                <span className="text-sm text-gray-500 sm:text-center dark:text-gray-400">
                    © 2024 <a href="#" className="hover:underline">YourCompany™</a>. All Rights Reserved.
                </span>
                <ul className="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0">
                    <li>
                        <a href="#" className="hover:underline me-4 md:me-6">About</a>
                    </li>
                    <li>
                        <a href="#" className="hover:underline me-4 md:me-6">Privacy Policy</a>
                    </li>
                    <li>
                        <a href="#" className="hover:underline">Contact</a>
                    </li>
                </ul>
            </div>
        </footer>
    )
}
